# Machine Learning - Student Performance
Valeria Zúñiga Mendoza | A01705435

In [49]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [50]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [51]:
# /content/drive/MyDrive/StudentPerfomance/ai_impact_student_performance_dataset.csv
%cd "/content/drive/MyDrive/StudentPerformance"

/content/drive/MyDrive/StudentPerformance

**Obtener el dataset**


Cargar dataset y dividirlo en test y train

In [52]:
df = pd.read_csv("ai_impact_student_performance_dataset.csv")
df

,student_id,age,gender,grade_level,study_hours_per_day,uses_ai,ai_usage_time_minutes,ai_tools_used,ai_usage_purpose,ai_dependency_score,...,concept_understanding_score,study_consistency_index,improvement_rate,sleep_hours,social_media_hours,tutoring_hours,class_participation_score,final_score,passed,performance_category
0,1,20,Female,1st Year,2.5,1,170,NaN,Exam Prep,10,...,4,9.0,8.1,7.2,1.5,4.6,6,36.8,0,Low
1,2,17,Male,12th,3.4,1,123,NaN,Notes,4,...,8,8.5,13.8,7.6,5.1,2.7,6,65.5,1,Medium
2,3,24,Male,3rd Year,0.8,0,35,Copilot,Doubt Solving,8,...,7,2.1,39.1,5.7,0.2,4.0,3,66.3,1,Medium
3,4,21,Female,12th,4.4,0,45,ChatGPT+Gemini,Notes,3,...,5,6.7,25.2,8.2,4.2,2.9,2,69.5,1,Medium
4,5,18,Other,3rd Year,3.5,1,21,ChatGPT+Gemini,Coding,2,...,5,5.4,2.7,8.7,0.2,2.9,2,49.7,1,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,7996,23,Male,3rd Year,3.0,0,178,Gemini,NaN,6,...,5,8.1,19.2,8.3,1.9,1.0,10,49.7,1,Low
7996,7997,21,Other,1st Year,3.3,0,63,Claude,Exam Prep,10,...,6,5.7,3.0,5.0,1.3,2.9,5,58.4,1,Medium
7997,7998,24,Male,3rd Year,1.6,0,113,ChatGPT,Coding,5,...,6,4.5,-18.0,5.0,3.5,0.1,9,69.1,1,Medium
7998,7999,22,Female,2nd Year,5.5,0,21,Copilot,Coding,5,...,8,3.4,-19.1,4.7,5.9,0.4,7,49.2,1,Low
7999,8000,15,Male,12th,4.6,0,42,NaN,NaN,9,...,6,9.7,-4.9,9.0,2.9,2.1,5,69.7,1,Medium

**Limpiar los datos**

Selecciono las columnas y no tengo que ajustar columnas por valores faltantes.

No tomé en cuenta las columnas de 'passed' y 'performance_category' porque son resultados que se saben después de saber la calificación final.

In [53]:
# Selección de las columnas a usar
columnas = ['age', 'gender', 'grade_level', 'study_hours_per_day', 'uses_ai', 'ai_usage_time_minutes', 'ai_usage_time_minutes',
            'ai_tools_used',	'ai_usage_purpose', 'ai_dependency_score','ai_generated_content_percentage', 'ai_prompts_per_week',
            'ai_ethics_score', 'last_exam_score', 'assignment_scores_avg', 'attendance_percentage', 'concept_understanding_score',
            'study_consistency_index',	'improvement_rate',	'sleep_hours', 'social_media_hours',	'tutoring_hours',
            'class_participation_score',	'final_score']
df_columnas_seleccionadas = df[columnas]
df_columnas_seleccionadas.shape

(8000, 24)

Separación del training set y test set de manera aleatoria

In [54]:
train_data, test_data = train_test_split(
    df_columnas_seleccionadas,
    test_size=0.2,
    random_state=42,
    shuffle=True
)

Como queremos predecir la calificación final y ese dato viene en la columna final_score, debemos quitar esa columna de los fragmentos de datos

In [55]:
test_labels_target = test_data["final_score"]
test_data = test_data.drop(columns=["final_score"])

train_labels_target = train_data["final_score"]
train_data = train_data.drop(columns=["final_score"])

In [56]:
train_data
test_data

,age,gender,grade_level,study_hours_per_day,uses_ai,ai_usage_time_minutes,ai_usage_time_minutes,ai_tools_used,ai_usage_purpose,ai_dependency_score,...,last_exam_score,assignment_scores_avg,attendance_percentage,concept_understanding_score,study_consistency_index,improvement_rate,sleep_hours,social_media_hours,tutoring_hours,class_participation_score
2215,19,Male,10th,4.6,0,179,179,Gemini,Doubt Solving,1,...,42,43.8,70.1,1,7.0,-8.5,5.7,5.1,4.3,9
2582,14,Female,11th,4.8,0,127,127,ChatGPT,Coding,3,...,92,74.9,95.6,10,9.4,-0.4,5.4,0.8,0.7,2
1662,20,Female,1st Year,2.4,1,116,116,Claude,Doubt Solving,10,...,77,60.5,97.1,6,3.4,-12.1,8.6,2.0,4.9,2
3027,14,Female,1st Year,1.2,1,123,123,NaN,Doubt Solving,9,...,71,53.7,53.0,7,8.5,12.5,7.4,5.7,4.5,10
4343,23,Male,11th,3.7,1,50,50,NaN,Exam Prep,2,...,85,88.0,95.3,5,6.3,-4.1,6.1,2.7,4.8,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1079,14,Male,11th,2.9,0,67,67,NaN,Homework,10,...,62,64.4,83.0,1,2.2,16.6,6.9,3.8,4.8,2
7979,17,Male,10th,2.7,0,125,125,Copilot,Homework,7,...,25,93.1,98.6,10,6.1,4.8,4.5,0.6,2.8,8
1115,22,Female,11th,4.7,1,8,8,Claude,NaN,3,...,43,69.3,51.1,10,8.9,23.6,7.8,3.6,0.5,1
6093,16,Female,2nd Year,1.3,0,123,123,ChatGPT+Gemini,Homework,4,...,65,97.0,72.3,8,1.8,-9.7,8.9,1.6,0.4,8
6832,17,Female,1st Year,4.1,0,73,73,ChatGPT,Doubt Solving,9,...,87,82.5,87.9,3,1.2,38.3,4.4,1.2,1.2,5

PREPROCESADO DE FEATURES


Como el modelo solo acepta números, debemos pasar columnas a binario.

Para 'gender' usaremos Label encoder, ya que tiene dos categorias (Female / Male) y no hay problema confusión de orden.

In [57]:
gender_encoder = LabelEncoder()

train_data['gender'] = gender_encoder.fit_transform(train_data['gender'])
test_data['gender'] = gender_encoder.transform(test_data['gender'])

In [58]:
train_data

,age,gender,grade_level,study_hours_per_day,uses_ai,ai_usage_time_minutes,ai_usage_time_minutes,ai_tools_used,ai_usage_purpose,ai_dependency_score,...,last_exam_score,assignment_scores_avg,attendance_percentage,concept_understanding_score,study_consistency_index,improvement_rate,sleep_hours,social_media_hours,tutoring_hours,class_participation_score
1467,23,0,3rd Year,0.8,1,175,175,NaN,Coding,5,...,56,91.0,76.4,4,2.9,30.9,6.1,3.6,2.6,5
5768,17,0,11th,5.8,1,142,142,Copilot,Notes,10,...,71,72.4,80.1,1,5.8,17.7,6.5,2.5,1.5,2
5714,15,0,12th,3.8,1,158,158,NaN,Coding,7,...,53,82.8,89.4,4,5.2,-13.7,7.3,5.9,4.0,8
1578,16,1,11th,4.6,1,64,64,ChatGPT,Exam Prep,4,...,90,46.4,50.5,10,6.3,28.5,4.5,2.0,1.8,7
6958,21,0,1st Year,1.7,1,79,79,ChatGPT+Gemini,Notes,9,...,99,98.3,98.1,5,1.1,-12.7,6.3,3.1,4.8,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5226,23,0,10th,0.9,1,121,121,ChatGPT,Coding,3,...,94,78.0,59.0,5,9.5,24.5,7.7,2.0,2.6,7
5390,22,1,1st Year,1.6,0,173,173,Gemini,Homework,6,...,54,67.3,90.2,7,3.8,24.2,7.7,1.4,0.6,4
860,14,1,3rd Year,5.0,1,80,80,NaN,Homework,6,...,32,65.7,77.6,3,7.0,-10.6,7.3,5.0,0.3,2
7603,15,1,11th,2.4,0,89,89,Copilot,Homework,1,...,87,86.0,64.6,5,9.7,2.6,8.6,3.7,1.5,8
7270,14,1,12th,5.9,1,178,178,Claude,NaN,9,...,27,72.1,63.6,8,2.5,23.0,6.7,5.4,4.0,6

Usamos OneHotEncoder para las columnas donde hay mas de dos categorias.

In [59]:
# Aplicar one-hot encoding a cada columna con data categórica

categorical_features = [
    'grade_level',
    'ai_tools_used',
    'ai_usage_purpose'
]

# One Hot Encoding para TRAIN
train_encoded = pd.get_dummies(
    train_data,
    columns=categorical_features,
    prefix=categorical_features
)

# One Hot Encoding para TEST
test_encoded = pd.get_dummies(
    test_data,
    columns=categorical_features,
    prefix=categorical_features
)

In [60]:
train_encoded

,age,gender,study_hours_per_day,uses_ai,ai_usage_time_minutes,ai_usage_time_minutes,ai_dependency_score,ai_generated_content_percentage,ai_prompts_per_week,ai_ethics_score,...,ai_tools_used_ChatGPT,ai_tools_used_ChatGPT+Gemini,ai_tools_used_Claude,ai_tools_used_Copilot,ai_tools_used_Gemini,ai_usage_purpose_Coding,ai_usage_purpose_Doubt Solving,ai_usage_purpose_Exam Prep,ai_usage_purpose_Homework,ai_usage_purpose_Notes
1467,23,0,0.8,1,175,175,5,50,10,3,...,False,False,False,False,False,True,False,False,False,False
5768,17,0,5.8,1,142,142,10,59,106,8,...,False,False,False,True,False,False,False,False,False,True
5714,15,0,3.8,1,158,158,7,56,32,10,...,False,False,False,False,False,True,False,False,False,False
1578,16,1,4.6,1,64,64,4,74,28,1,...,True,False,False,False,False,False,False,True,False,False
6958,21,0,1.7,1,79,79,9,42,63,7,...,False,True,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5226,23,0,0.9,1,121,121,3,46,55,8,...,True,False,False,False,False,True,False,False,False,False
5390,22,1,1.6,0,173,173,6,31,112,4,...,False,False,False,False,True,False,False,False,True,False
860,14,1,5.0,1,80,80,6,62,64,10,...,False,False,False,False,False,False,False,False,True,False
7603,15,1,2.4,0,89,89,1,60,77,6,...,False,False,False,True,False,False,False,False,True,False
7270,14,1,5.9,1,178,178,9,25,106,3,...,False,False,True,False,False,False,False,False,False,False

In [61]:
test_encoded

,age,gender,study_hours_per_day,uses_ai,ai_usage_time_minutes,ai_usage_time_minutes,ai_dependency_score,ai_generated_content_percentage,ai_prompts_per_week,ai_ethics_score,...,ai_tools_used_ChatGPT,ai_tools_used_ChatGPT+Gemini,ai_tools_used_Claude,ai_tools_used_Copilot,ai_tools_used_Gemini,ai_usage_purpose_Coding,ai_usage_purpose_Doubt Solving,ai_usage_purpose_Exam Prep,ai_usage_purpose_Homework,ai_usage_purpose_Notes
2215,19,1,4.6,0,179,179,1,50,79,5,...,False,False,False,False,True,False,True,False,False,False
2582,14,0,4.8,0,127,127,3,55,39,2,...,True,False,False,False,False,True,False,False,False,False
1662,20,0,2.4,1,116,116,10,39,13,1,...,False,False,True,False,False,False,True,False,False,False
3027,14,0,1.2,1,123,123,9,54,54,8,...,False,False,False,False,False,False,True,False,False,False
4343,23,1,3.7,1,50,50,2,35,92,5,...,False,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1079,14,1,2.9,0,67,67,10,72,4,7,...,False,False,False,False,False,False,False,False,True,False
7979,17,1,2.7,0,125,125,7,59,18,4,...,False,False,False,True,False,False,False,False,True,False
1115,22,0,4.7,1,8,8,3,1,75,8,...,False,False,True,False,False,False,False,False,False,False
6093,16,0,1.3,0,123,123,4,33,117,10,...,False,True,False,False,False,False,False,False,True,False
6832,17,0,4.1,0,73,73,9,10,43,1,...,True,False,False,False,False,False,True,False,False,False